name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun install --frozen-lockfile
      - run: bun run check
