name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2.2.0
      - run: bun install --frozen-lockfile
      - run: bun run build
        env:
          BASE_PATH: ${{ vars.BASE_PATH }}
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          clean-exclude: |
            pr-preview/
